import json
import os

# Asegurar que existe la carpeta destino
output_dir = r"c:\Users\BlandskronNotebook\Documents\blandskron\licenciatura-en-fisica\05-calculo-2\leccion-1"
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, "integral-de-riemann.ipynb")

notebook = {
  "cells": [],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 2
}

def add_markdown(source_list):
    notebook["cells"].append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in source_list]
    })

def add_code(source_list):
    notebook["cells"].append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source_list]
    })

# --- CELL 1: HEADER ---
add_markdown([
    "# Lección 1: La Integral de Riemann y sus Extensiones",
    "### Cálculo II y Fundamentos de la Física Matemática",
    "",
    "---",
    "",
    "Este cuaderno abarca el estudio formal, riguroso e interactivo de la **Integral de Riemann**, sus teoremas fundamentales y sus aplicaciones en la física y las matemáticas. Partiendo de las nociones básicas de particiones y sumas de Riemann, analizaremos las condiciones de integrabilidad y la uniforme continuidad. Desarrollaremos la teoría detrás del Teorema del Valor Medio para integrales y los Teoremas Fundamentales del Cálculo, para luego resolver y visualizar aplicaciones geométricas y físicas (longitud de arco, potencial electrostático, mecánica cuántica). Finalmente, exploraremos las extensiones clásicas de Riemann-Stieltjes y Lebesgue, comparando sus metodologías y límites de validez.",
    "",
    "---"
])

# --- CELL 2: OBJECTIVES ---
add_markdown([
    "## Objetivos de Aprendizaje",
    "",
    "Al finalizar esta lección, serás capaz de:",
    "1. **Definir** formalmente la integral de Riemann como el límite de sumas de Riemann cuando la norma de la partición tiende a cero.",
    "2. **Demostrar** analíticamente y verificar numéricamente las propiedades de linealidad, aditividad, acotamiento y monotonía de la integral.",
    "3. **Explicar** la relación entre la continuidad de una función y su integrabilidad, diferenciando entre continuidad simple y uniforme.",
    "4. **Aplicar** los Teoremas Fundamentales del Cálculo (Barrow y derivada de la función de acumulación) para evaluar integrales analíticamente y mediante SymPy.",
    "5. **Implementar** algoritmos numéricos para la aproximación de integrales (Trapecio y Simpson) y analizar su velocidad de convergencia mediante diagramas log-log.",
    "6. **Modelar y resolver** problemas reales de física y geometría, tales como el potencial eléctrico de distribuciones lineales de carga y probabilidades cuánticas, identificando y corrigiendo erratas de textos estándar de la literatura.",
    "7. **Comparar** los fundamentos de las integrales de Riemann, Riemann-Stieltjes y Lebesgue."
])

# --- CELL 3: DEFINITION AND CONCEPTS ---
add_markdown([
    "## 1. Definición y Conceptos Básicos",
    "",
    "### 1.1 Partición de un Intervalo y Nodos",
    "Sea $[a, b]$ un intervalo cerrado y acotado en los números reales $\\mathbb{R}$. Una **partición** $P$ de $[a, b]$ es un conjunto finito de puntos ordenados:",
    "$$P = \\{x_0, x_1, x_2, \\dots, x_{n-1}, x_n\\}$$",
    "tales que:",
    "$$a = x_0 < x_1 < x_2 < \\dots < x_{n-1} < x_n = b$$",
    "Los puntos $x_i$ se denominan **nodos** de la partición. Estos nodos dividen a $[a, b]$ en $n$ subintervalos cerrados de la forma $[x_{i-1}, x_i]$. La longitud de cada subintervalo se denota por $\\Delta x_i = x_i - x_{i-1}$ para $i = 1, 2, \\dots, n$.",
    "",
    "Definimos la **norma de la partición** $P$, denotada por $\\|P\\|$, como la longitud del subintervalo más grande:",
    "$$\\|P\\| = \\max_{1 \\le i \\le n} \\Delta x_i$$",
    "Una partición se dice **regular** si todos los subintervalos tienen la misma longitud, en cuyo caso $\\Delta x_i = \\Delta x = \\frac{b-a}{n}$ para todo $i$.",
    "",
    "### 1.2 Sumas de Riemann",
    "Para una función acotada $f: [a, b] \\to \\mathbb{R}$, y dada una partición $P$, elegimos en cada subintervalo $[x_{i-1}, x_i]$ un **punto muestra** $c_i \\in [x_{i-1}, x_i]$. La **suma de Riemann** de $f$ asociada a la partición $P$ y a la elección de puntos muestra $\\{c_i\\}$ se define como:",
    "$$S(f, P, \\{c_i\\}) = \\sum_{i=1}^n f(c_i) \\Delta x_i$$",
    "Las tres elecciones comunes para los puntos muestra son:",
    "- **Suma por la izquierda (Left Riemann Sum):** $c_i = x_{i-1}$",
    "- **Suma por la derecha (Right Riemann Sum):** $c_i = x_i$",
    "- **Suma del punto medio (Midpoint Riemann Sum):** $c_i = \\frac{x_{i-1} + x_i}{2}$",
    "",
    "### 1.3 Límite e Integrabilidad de Riemann",
    "Se dice que la función $f$ es **integrable según Riemann** en $[a, b]$ si existe un número real $I$ tal que, para todo $\\epsilon > 0$, existe un $\\delta > 0$ tal que si $P$ es cualquier partición de $[a, b]$ con $\\|P\\| < \\delta$, entonces:",
    "$$\\left| \\sum_{i=1}^n f(c_i) \\Delta x_i - I \\right| < \\epsilon$$",
    "independientemente de la elección de los puntos muestra $c_i$. En este caso, escribimos:",
    "$$I = \\int_a^b f(x) dx = \\lim_{\\|P\\| \\to 0} \\sum_{i=1}^n f(c_i) \\Delta x_i$$"
])

# --- CELL 4: CODE - RIEMANN SUMS VISUALIZATION ---
add_code([
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "import sympy as sp",
    "from scipy.integrate import quad",
    "",
    "# Configuración del estilo visual premium",
    "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')",
    "plt.rcParams.update({",
    "    'font.family': 'sans-serif',",
    "    'font.size': 11,",
    "    'axes.labelsize': 12,",
    "    'axes.titlesize': 13,",
    "    'xtick.labelsize': 10,",
    "    'ytick.labelsize': 10,",
    "    'figure.titlesize': 14",
    "})",
    "",
    "# Función didáctica: f(x) = x * sin(x) + 2 en [0, 6]",
    "def f_rie(x):",
    "    return x * np.sin(x) + 2",
    "",
    "a, b = 0.0, 6.0",
    "n = 10  # Número de subintervalos",
    "dx = (b - a) / n",
    "",
    "x_continuous = np.linspace(a, b, 500)",
    "y_continuous = f_rie(x_continuous)",
    "",
    "# Puntos de partición",
    "x_partition = np.linspace(a, b, n + 1)",
    "",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5.5), sharey=True)",
    "methods = ['Izquierda', 'Derecha', 'Punto Medio']",
    "",
    "for i, method in enumerate(methods):",
    "    ax = axes[i]",
    "    ax.plot(x_continuous, y_continuous, 'b-', linewidth=2.5, label='$f(x) = x \\\\sin(x) + 2$')",
    "    ",
    "    if method == 'Izquierda':",
    "        c_i = x_partition[:-1]",
    "        align = 'edge'",
    "        bar_w = dx",
    "    elif method == 'Derecha':",
    "        c_i = x_partition[1:]",
    "        align = 'edge'",
    "        bar_w = -dx",
    "    else:  # Punto Medio",
    "        c_i = 0.5 * (x_partition[:-1] + x_partition[1:])",
    "        align = 'center'",
    "        bar_w = dx",
    "        ",
    "    y_i = f_rie(c_i)",
    "    riemann_sum = np.sum(y_i) * dx",
    "    ",
    "    # Graficar rectángulos de aproximación",
    "    ax.bar(c_i, y_i, width=bar_w, align=align, alpha=0.3, ",
    "           edgecolor='darkblue', color='skyblue', label=f'Suma = {riemann_sum:.4f}')",
    "    ax.scatter(c_i, y_i, color='red', s=35, zorder=5, label='Puntos muestra $c_i$')",
    "    ",
    "    ax.set_title(f'Suma por la {method} ($n = {n}$)', fontweight='bold')",
    "    ax.set_xlabel('$x$')",
    "    if i == 0:",
    "        ax.set_ylabel('$f(x)$')",
    "    ax.legend(loc='upper left', frameon=True)",
    "    ax.grid(True, linestyle='--', alpha=0.5)",
    "",
    "plt.tight_layout()",
    "plt.show()"
])

# --- CELL 5: ANTIDERIVATIVES ---
add_markdown([
    "## 2. La Antiderivada y su Relación con la Integral",
    "",
    "### 2.1 Concepto de Antiderivada",
    "Una función $F$ se llama **antiderivada** o **primitiva** de $f$ en un intervalo $I$ si:",
    "$$F'(x) = f(x) \\quad \\forall x \\in I$$",
    "Si $F$ es una antiderivada de $f$, la familia completa de antiderivadas viene dada por $F(x) + C$, donde $C \\in \\mathbb{R}$ es la constante de integración. Esta relación es puramente diferencial. La conexión profunda entre este concepto y el área acumulada (la integral de Riemann) se establece mediante el **Teorema Fundamental del Cálculo**.",
    "",
    "### 2.2 Ecuaciones Diferenciales Elementales",
    "Cualquier problema donde se busque encontrar una función $y(x)$ a partir de su derivada $y'(x) = f(x)$ representa la ecuación diferencial ordinaria más simple. Su solución es la integral indefinida:",
    "$$y(x) = \\int f(x) dx = F(x) + C$$",
    "Si se proporciona una condición inicial $y(x_0) = y_0$, se puede determinar la constante única $C$."
])

# --- CELL 6: PROPERTIES OF THE INTEGRAL ---
add_markdown([
    "## 3. Propiedades de la Integral de Riemann",
    "",
    "Sean $f$ y $g$ funciones acotadas e integrables en $[a, b]$, y sea $k \\in \\mathbb{R}$ una constante:",
    "",
    "1. **Linealidad (Factor Constante):**",
    "   $$\\int_a^b k f(x) dx = k \\int_a^b f(x) dx$$",
    "2. **Linealidad (Suma/Resta):**",
    "   $$\\int_a^b [f(x) \\pm g(x)] dx = \\int_a^b f(x) dx \\pm \\int_a^b g(x) dx$$",
    "3. **Aditividad del Intervalo:** Si $c \\in (a, b)$, entonces $f$ es integrable en $[a, c]$ y en $[c, b]$, y se cumple que:",
    "   $$\\int_a^b f(x) dx = \\int_a^c f(x) dx + \\int_c^b f(x) dx$$",
    "4. **Monotonía (Comparación):** Si $f(x) \\le g(x)$ para todo $x \\in [a, b]$:",
    "   $$\\int_a^b f(x) dx \\le \\int_a^b g(x) dx$$",
    "5. **Desigualdad del Valor Absoluto:** Si $f$ es integrable, $|f|$ es integrable y:",
    "   $$\\left| \\int_a^b f(x) dx \\right| \\le \\int_a^b |f(x)| dx$$",
    "6. **Acotamiento:** Si $m \\le f(x) \\le M$ para todo $x \\in [a, b]$:",
    "   $$m(b-a) \\le \\int_a^b f(x) dx \\le M(b-a)$$",
    "7. **Invariancia ante Desplazamiento:**",
    "   $$\\int_a^b f(x) dx = \\int_{a+c}^{b+c} f(x-c) dx$$"
])

# --- CELL 7: CODE - PROPERTIES VERIFICATION ---
add_code([
    "# Validación numérica de la Aditividad y Desigualdad del Valor Absoluto",
    "a, b = 0.0, 3.0",
    "c = 1.5",
    "",
    "# f(x) = x^3 - 2x^2",
    "def f_prop(x):",
    "    return x**3 - 2*x**2",
    "",
    "# 1. Verificar Aditividad del Intervalo",
    "int_total, _ = quad(f_prop, a, b)",
    "int_part1, _ = quad(f_prop, a, c)",
    "int_part2, _ = quad(f_prop, c, b)",
    "",
    "print(\"=== VALIDACIÓN DE PROPIEDADES ===\")",
    "print(f\"Integral [a, b]:  {int_total:.8f}\")",
    "print(f\"Suma de partes:   {int_part1 + int_part2:.8f} (Parte 1: {int_part1:.4f}, Parte 2: {int_part2:.4f})\")",
    "assert np.isclose(int_total, int_part1 + int_part2, atol=1e-12)",
    "print(\"-> Propiedad de Aditividad verificada con éxito.\\n\")",
    "",
    "# 2. Verificar Desigualdad del Valor Absoluto",
    "abs_int = abs(int_total)",
    "int_abs, _ = quad(lambda x: abs(f_prop(x)), a, b)",
    "",
    "print(f\"Valor absoluto de la integral: |I| = {abs_int:.8f}\")",
    "print(f\"Integral del valor absoluto:  I(|f|) = {int_abs:.8f}\")",
    "print(f\"Diferencia:                   {int_abs - abs_int:.8f}\")",
    "assert abs_int <= int_abs",
    "print(\"-> Desigualdad del Valor Absoluto verificada con éxito.\")"
])

# --- CELL 8: FUNDAMENTAL THEOREMS ---
add_markdown([
    "## 4. Teoremas Fundamentales de la Integral de Riemann",
    "",
    "### 4.1 Teorema del Valor Medio para Integrales",
    "Si $f$ es una función continua en el intervalo cerrado $[a, b]$, entonces existe un número $c$ en el intervalo abierto $(a, b)$ tal que:",
    "$$f(c) = \\frac{1}{b-a} \\int_a^b f(x) dx$$",
    "El valor $f(c)$ se denomina **valor medio** de la función $f$ en el intervalo $[a, b]$. Geométricamente, esto significa que existe un rectángulo con base $b-a$ y altura $f(c)$ cuya área es exactamente igual al área bajo la curva de $f$ de $a$ a $b$.",
    "",
    "### 4.2 Primer Teorema Fundamental del Cálculo (FTC 1)",
    "Sea $f$ una función continua en $[a, b]$. Si definimos la **función de acumulación** $g(x)$ como:",
    "$$g(x) = \\int_a^x f(t) dt \\quad \\forall x \\in [a, b]$$",
    "entonces $g(x)$ es continua en $[a, b]$, derivable en $(a, b)$, y su derivada es:",
    "$$g'(x) = f(x)$$",
    "Es decir, la derivación es la operación inversa de la integración. En términos generales, usando la regla de la cadena, si los límites de integración dependen de funciones $u(x)$ y $v(x)$, tenemos la **Regla de Leibniz**:",
    "$$\\frac{d}{dx} \\left[ \\int_{u(x)}^{v(x)} f(t) dt \\right] = f(v(x)) v'(x) - f(u(x)) u'(x)$$",
    "",
    "### 4.3 Segundo Teorema Fundamental del Cálculo (Regla de Barrow)",
    "Si $f$ es continua en $[a, b]$ y $F$ es cualquier antiderivada de $f$ en $[a, b]$ (de modo que $F' = f$), entonces:",
    "$$\\int_a^b f(x) dx = F(b) - F(a)$$"
])

# --- CELL 9: CODE - SYMPY VERIFICATION ---
add_code([
    "# Verificación analítica del FTC mediante SymPy",
    "import sympy as sp",
    "",
    "x_sym, t_sym = sp.symbols('x t')",
    "",
    "# 1. Definir una función f(t) = t^2 * cos(t)",
    "f_sym = t_sym**2 * sp.cos(t_sym)",
    "",
    "# Definir los límites variables de integración: de x a x^2",
    "u_limit = x_sym",
    "v_limit = x_sym**2",
    "",
    "# Integral de acumulación",
    "G_accumulation = sp.integrate(f_sym, (t_sym, u_limit, v_limit))",
    "",
    "# Derivada de la acumulación directa",
    "dG_direct = sp.diff(G_accumulation, x_sym)",
    "",
    "# Regla de Leibniz analítica: f(v(x))*v'(x) - f(u(x))*u'(x)",
    "leibniz_term1 = f_sym.subs(t_sym, v_limit) * sp.diff(v_limit, x_sym)",
    "leibniz_term2 = f_sym.subs(t_sym, u_limit) * sp.diff(u_limit, x_sym)",
    "dG_leibniz = sp.simplify(leibniz_term1 - leibniz_term2)",
    "",
    "print(\"=== VERIFICACIÓN DEL FTC / REGLA DE LEIBNIZ ===\")",
    "print(f\"Función integranda f(t): {f_sym}\")",
    "print(f\"Límites: u(x) = {u_limit}, v(x) = {v_limit}\\n\")",
    "print(f\"Función de acumulación G(x):\\n{sp.pretty(G_accumulation)}\\n\")",
    "print(f\"Derivada de G(x) por evaluación directa:\\n{sp.pretty(dG_direct)}\\n\")",
    "print(f\"Derivada de G(x) por regla de Leibniz:\\n{sp.pretty(dG_leibniz)}\\n\")",
    "",
    "# Comprobar equivalencia",
    "is_equivalent = sp.simplify(dG_direct - dG_leibniz) == 0",
    "print(f\"¿Son equivalentes ambos métodos?: {is_equivalent}\")",
    "assert is_equivalent"
])

# --- CELL 10: CONTINUITY AND INTEGRABILITY ---
add_markdown([
    "## 5. Relación entre la Integral de Riemann y la Continuidad",
    "",
    "### 5.1 Continuidad Uniforme",
    "Una función $f$ es **uniformemente continua** en un intervalo $I$ si para todo $\\epsilon > 0$ existe un $\\delta > 0$ tal que para cualesquiera $x, y \\in I$ con $|x - y| < \\delta$, se cumple que $|f(x) - f(y)| < \\epsilon$.",
    "",
    "A diferencia de la continuidad estándar (donde $\\delta$ depende tanto de $\\epsilon$ como del punto $x_0$), en la continuidad uniforme el $\\delta$ depende **únicamente** de $\\epsilon$ para todo el intervalo.",
    "",
    "**Teorema de Heine-Cantor:** Si una función $f$ es continua en un intervalo cerrado y acotado $[a, b]$, entonces es uniformemente continua en $[a, b]$.",
    "",
    "Esta propiedad es crucial para la teoría de Riemann, ya que garantiza que las sumas de Riemann converjan de forma consistente al valor de la integral a medida que la norma de la partición tiende a cero, sin importar cómo se elijan los nodos o puntos muestra.",
    "",
    "### 5.2 Garantía de Finitud de la Integral",
    "Si $f$ es continua en un intervalo cerrado $[a, b]$, por el **Teorema de Weierstrass** está acotada en ese intervalo, es decir, existe una constante $M > 0$ tal que $|f(x)| \\le M$ para todo $x \\in [a, b]$. Como consecuencia, las sumas de Riemann no pueden crecer indefinidamente, garantizando que el límite de las sumas sea un número real finito:",
    "$$\\left| \\int_a^b f(x) dx \\right| \\le M(b-a)$$"
])

# --- CELL 11: APPROXIMATION METHODS ---
add_markdown([
    "## 6. Métodos de Aproximación Numérica",
    "",
    "Cuando la integral no se puede evaluar analíticamente mediante funciones elementales, se recurre a aproximaciones numéricas (cuadratura). Dos métodos clásicos son:",
    "",
    "### 6.1 Regla del Trapecio",
    "Consiste en aproximar la curva mediante segmentos de recta sobre una partición regular de $n$ subintervalos de ancho $h = \\frac{b-a}{n}$. Al sumar las áreas de los trapecios resultantes, se obtiene:",
    "$$\\int_a^b f(x) dx \\approx T_n = \\frac{h}{2} \\left[ f(a) + 2 \\sum_{i=1}^{n-1} f(x_i) + f(b) \\right]$$",
    "**Cota de Error:** Si $f \\in C^2[a, b]$, existe un $\\xi \\in [a, b]$ tal que el error $E_T$ es de orden $O(h^2)$:",
    "$$E_T = -\\frac{(b-a)^3}{12 n^2} f''(\\xi)$$",
    "",
    "### 6.2 Regla de Simpson (1/3)",
    "Aproxima la curva en pares de subintervalos contiguos mediante parábolas (polinomios interpolantes de segundo grado). Requiere que el número de intervalos $n$ sea **par**. La fórmula es:",
    "$$\\int_a^b f(x) dx \\approx S_n = \\frac{h}{3} \\left[ f(a) + 4 \\sum_{i=1, 3, 5}^{n-1} f(x_i) + 2 \\sum_{i=2, 4, 6}^{n-2} f(x_i) + f(b) \\right]$$",
    "**Cota de Error:** Si $f \\in C^4[a, b]$, existe un $\\eta \\in [a, b]$ tal que el error $E_S$ es de orden $O(h^4)$:",
    "$$E_S = -\\frac{(b-a)^5}{180 n^4} f^{(4)}(\\eta)$$"
])

# --- CELL 12: CODE - NUMERICAL INTERPOLATION & CONVERGENCE ---
add_code([
    "def trapezoid_rule(f, a, b, n):",
    "    h = (b - a) / n",
    "    x = np.linspace(a, b, n + 1)",
    "    y = f(x)",
    "    return (h / 2.0) * (y[0] + 2.0 * np.sum(y[1:-1]) + y[-1])",
    "",
    "def simpson_rule(f, a, b, n):",
    "    if n % 2 != 0:",
    "        n += 1  # Ajustar a par para la regla de Simpson 1/3",
    "    h = (b - a) / n",
    "    x = np.linspace(a, b, n + 1)",
    "    y = f(x)",
    "    return (h / 3.0) * (y[0] + 4.0 * np.sum(y[1:-1:2]) + 2.0 * np.sum(y[2:-2:2]) + y[-1])",
    "",
    "# Función de prueba: f(x) = cos(x) en [0, pi/2]. Integral exacta = sin(pi/2) - sin(0) = 1.0",
    "f_test = np.cos",
    "a_test, b_test = 0.0, np.pi / 2.0",
    "exact_val = 1.0",
    "",
    "n_values = np.array([4, 8, 16, 32, 64, 128, 256, 512, 1024])",
    "err_trap = []",
    "err_simp = []",
    "",
    "for n_val in n_values:",
    "    val_trap = trapezoid_rule(f_test, a_test, b_test, n_val)",
    "    val_simp = simpson_rule(f_test, a_test, b_test, n_val)",
    "    ",
    "    err_trap.append(abs(val_trap - exact_val))",
    "    err_simp.append(abs(val_simp - exact_val))",
    "",
    "# Graficar tasas de convergencia (Escala Log-Log)",
    "plt.figure(figsize=(10, 6))",
    "plt.loglog(n_values, err_trap, 'o-', color='royalblue', linewidth=2, label='Regla del Trapecio')",
    "plt.loglog(n_values, err_simp, 's-', color='crimson', linewidth=2, label='Regla de Simpson')",
    "",
    "# Rectas de referencia teóricas: O(n^-2) y O(n^-4)",
    "plt.loglog(n_values, err_trap[0] * (n_values[0] / n_values)**2, '--', color='blue', alpha=0.5, label='Pendiente teórica $O(n^{-2})$')",
    "plt.loglog(n_values, err_simp[0] * (n_values[0] / n_values)**4, '--', color='red', alpha=0.5, label='Pendiente teórica $O(n^{-4})$')",
    "",
    "plt.title('Estudio de Convergencia del Error Numérico (Escala Log-Log)', fontweight='bold')",
    "plt.xlabel('Número de intervalos $n$')",
    "plt.ylabel('Error absoluto $|I_{aprox} - I_{exacta}|$')",
    "plt.grid(True, which=\"both\", linestyle='--', alpha=0.5)",
    "plt.legend(frameon=True)",
    "plt.tight_layout()",
    "plt.show()"
])

# --- CELL 13: CRITERION OF INTEGRABILITY ---
add_markdown([
    "## 7. Criterio de Integrabilidad de Riemann",
    "",
    "El **criterio clásico de integrabilidad** establece que una función $f$ acotada en $[a, b]$ es integrable si y solo si el conjunto de sus puntos de discontinuidad tiene **medida cero** (Teorema de Lebesgue). En términos prácticos para Cálculo II, esto significa que:",
    "",
    "- Toda función continua en $[a, b]$ es integrable.",
    "- Toda función monótona en $[a, b]$ es integrable (incluso con infinitas discontinuidades).",
    "- Toda función con un número finito de discontinuidades de **salto finito** o **evitables** es integrable.",
    "",
    "Si una función tiene discontinuidades de tipo infinito (asíntotas) dentro del intervalo, la integral de Riemann estándar no se puede definir directamente, debiéndose recurrir al concepto de **Integrales Impropias**."
])

# --- CELL 14: APPLICATIONS ---
add_markdown([
    "## 8. Aplicaciones Matemáticas y Físicas",
    "",
    "### 8.1 Cálculo de Áreas",
    "El área $A$ de la región encerrada por las curvas $y = f(x)$ y $y = g(x)$ entre $x = a$ y $x = b$, donde $f(x) \\ge g(x)$, es:",
    "$$A = \\int_a^b [f(x) - g(x)] dx$$",
    "",
    "### 8.2 Volumen de Sólidos de Revolución (Método de los Discos)",
    "Al rotar la región acotada por la curva $y = f(x)$ en torno al eje $x$ entre $a$ y $b$, el volumen $V$ del sólido generado es la suma infinitesimal de los volúmenes de discos delgados con radio $f(x)$ y espesor $dx$:",
    "$$V = \\pi \\int_a^b [f(x)]^2 dx$$",
    "",
    "### 8.3 Longitud de Arco",
    "La longitud $S$ de una curva suave parametrizada por $y = f(x)$ en el intervalo $[a, b]$ se deduce del teorema de Pitágoras infinitesimal $ds = \\sqrt{dx^2 + dy^2}$:",
    "$$S = \\int_a^b \\sqrt{1 + [f'(x)]^2} dx$$",
    "",
    "### 8.4 Centro de Masa de una Barra Unidimensional",
    "Sea una barra delgada de longitud $L$ y densidad lineal de masa variable $\\rho(x)$ distribuida a lo largo del eje $x$ desde $x=0$ a $x=L$. Su masa total $m$ y su coordenada del centro de masa $\\bar{x}$ son:",
    "$$m = \\int_0^L \\rho(x) dx, \\quad \\bar{x} = \\frac{1}{m} \\int_0^L x \\rho(x) dx$$",
    "",
    "### 8.5 Trabajo Mecánico de una Fuerza Variable",
    "El trabajo $W$ realizado por una fuerza variable unidimensional $F(x)$ para mover un objeto desde $x=a$ hasta $x=b$ es:",
    "$$W = \\int_a^b F(x) dx$$"
])

# --- CELL 15: CODE - ARC LENGTH POLYGONAL APPROXIMATION ---
add_code([
    "# Simulación interactiva de Longitud de Arco por aproximaciones poligonales",
    "# Curva y = sqrt(x) en [0, 4]",
    "def f_curve(x):",
    "    return np.sqrt(x)",
    "",
    "a_c, b_c = 0.0, 4.0",
    "x_c_dense = np.linspace(a_c, b_c, 500)",
    "y_c_dense = f_curve(x_c_dense)",
    "",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 6))",
    "n_segs_list = [4, 20]",
    "",
    "for idx, n_segs in enumerate(n_segs_list):",
    "    ax = axes[idx]",
    "    ax.plot(x_c_dense, y_c_dense, 'b-', linewidth=2, label='Curva $y=\\\\sqrt{x}$')",
    "    ",
    "    x_nodes = np.linspace(a_c, b_c, n_segs + 1)",
    "    y_nodes = f_curve(x_nodes)",
    "    ",
    "    # Calcular la longitud poligonal",
    "    poly_length = 0.0",
    "    for i in range(n_segs):",
    "        x_p, y_p = x_nodes[i], y_nodes[i]",
    "        x_n, y_n = x_nodes[i+1], y_nodes[i+1]",
    "        dist = np.sqrt((x_n - x_p)**2 + (y_n - y_p)**2)",
    "        poly_length += dist",
    "        # Graficar segmento",
    "        ax.plot([x_p, x_n], [y_p, y_n], 'r-', marker='o', markersize=4, alpha=0.8)",
    "        ",
    "    ax.plot([], [], 'r-', marker='o', label=f'Poligonal (L = {poly_length:.5f})')",
    "    ax.set_title(f'Aproximación con {n_segs} Segmentos', fontweight='bold')",
    "    ax.set_xlabel('$x$')",
    "    ax.set_ylabel('$y$')",
    "    ax.legend(frameon=True)",
    "    ax.grid(True, linestyle='--', alpha=0.5)",
    "",
    "# Longitud exacta calculada analíticamente en Test:",
    "# S = 4.64678",
    "print(\"=== CONVERGENCIA DE LONGITUD DE ARCO ===\")",
    "print(\"Longitud exacta (analítica): 4.64678376\")",
    "plt.tight_layout()",
    "plt.show()"
])

# --- CELL 16: CASES ERRATA STUDY ---
add_markdown([
    "## 9. Análisis de Casos de Estudio y Corrección de Erratas",
    "",
    "Una de las mayores virtudes de la física computacional es su capacidad para detectar erratas e inconsistencias en la literatura mediante la confrontación del análisis simbólico y la integración numérica. A continuación, analizamos dos casos del material original.",
    "",
    "### Caso de Estudio 1: Potencial Electrostático (pág. 14 del PDF)",
    "**Enunciado del PDF:** Se tiene una distribución lineal de carga $\\lambda(x') = 2x'$ a lo largo del eje $x'$ desde $x'=0$ m hasta $x'=3$ m. Se desea calcular el potencial eléctrico $V(x)$ en el punto $x=4$ m. La fórmula del potencial es:",
    "$$V(x) = k \\int_{x'_{min}}^{x'_{max}} \\frac{\\lambda(x') dx'}{|x - x'|} \\implies V(4) = k \\int_0^3 \\frac{2x'}{|4 - x'|} dx'$$",
    "",
    "**Error en el Texto original:**",
    "El texto propone que para evaluar la integral con valor absoluto se debe dividir en dos partes, extendiendo incorrectamente la integral hasta $x'=4$ e integrando hacia atrás:",
    "$$V(4) = k \\left( \\int_0^4 \\frac{2x'}{4-x'} dx' + \\int_4^3 \\frac{2x'}{x'-4} dx' \\right)$$",
    "Esto es un **grave error conceptual y matemático** por dos razones:",
    "1. **Extensión Ficticia del Soporte:** La distribución de carga existe únicamente en $[0, 3]$. No hay carga en $(3, 4]$. Integrar hasta 4 inventa carga que no existe.",
    "2. **Singularidad Divergente:** Al forzar la integral hasta $x'=4$, el denominador se anula en el extremo superior. La integral $\\int_0^4 \\frac{2x'}{4-x'} dx'$ posee una singularidad logarítmica y diverge hacia $+\\infty$. El autor ignora esta divergencia y evalúa $\\ln|0|$ como si fuera finito o cancelara con otro término, obteniendo un valor erróneo de $V(4) \\approx -8.912\\,k$.",
    "",
    "**Resolución Correcta:**",
    "Dado que $x' \\in [0, 3]$, siempre se cumple que $x' < 4$, por lo tanto, $|4 - x'| = 4 - x'$. La integral no requiere división de intervalos y es perfectamente regular y acotada:",
    "$$V(4) = k \\int_0^3 \\frac{2x'}{4-x'} dx'$$",
    "Haciendo la división del integrando o la sustitución $u = 4 - x'$ ($dx' = -du$):",
    "$$\\int_0^3 \\frac{2x'}{4-x'} dx' = \\int_0^3 \\left( -2 + \\frac{8}{4-x'} \\right) dx' = \\left[ -2x' - 8\\ln(4-x') \\right]_0^3 = (-6 - 8\\ln 1) - (0 - 8\\ln 4) = 8\\ln 4 - 6$$",
    "Dado que $\\ln 4 \\approx 1.386294$, obtenemos un valor positivo y físicamente coherente:",
    "$$V(4) = k(8\\ln 4 - 6) \\approx 5.09035\\,k$$",
    "",
    "---",
    "",
    "### Caso de Estudio 2: Caja Cuántica Unidimensional (pág. 15-16 del PDF)",
    "**Enunciado del PDF:** Calcular la probabilidad de encontrar una partícula confinada en una caja unidimensional de longitud $L$, en la región $0 \\le x \\le L/2$, para el nivel de energía fundamental ($n=1$). La función de onda es $\\Psi(x) = \\sqrt{\\frac{2}{L}} \\sin\\left(\\frac{\\pi x}{L}\\right)$.",
    "",
    "**Error en el Texto original:**",
    "El texto original realiza una serie de tres errores matemáticos en cascada:",
    "1. **Factor de Simetría Erróneo:** Escribe $P = \\frac{4}{L} \\int_0^{L/2} \\sin^2\\left(\\frac{\\pi x}{L}\\right) dx$, argumentando que es una función par y duplicando el coeficiente (debería ser $\\frac{2}{L}$ y no $\\frac{4}{L}$, ya que el dominio de la caja es $[0, L]$, no simétrico respecto a $0$).",
    "2. **Error de Integración:** Escribe el término del integrando como $\\frac{L}{2\\pi}\\sin\\left(\\frac{2\\pi x}{L}\\right)$ con un divisor $2\\pi$ en lugar del correcto $4\\pi$.",
    "3. **Falsa Evaluación Trigonométrica:** Evalúa $\\sin(\\pi)$ como si fuera $1$ en lugar del valor real $0$, concluyendo que $P = 1 - 2/\\pi \\approx 0.363$.",
    "",
    "**Resolución Correcta:**",
    "Físicamente, la densidad de probabilidad $|\\Psi(x)|^2 = \\frac{2}{L}\\sin^2\\left(\\frac{\\pi x}{L}\\right)$ es simétrica respecto al centro de la caja $x = L/2$. Por lo tanto, la probabilidad de encontrar la partícula en la mitad izquierda de la caja $[0, L/2]$ debe ser exactamente **0.5**.",
    "Analíticamente:",
    "$$P = \\int_0^{L/2} \\frac{2}{L} \\sin^2\\left(\\frac{\\pi x}{L}\\right) dx = \\frac{2}{L} \\int_0^{L/2} \\left( \\frac{1 - \\cos(2\\pi x / L)}{2} \\right) dx = \\frac{1}{L} \\left[ x - \\frac{L}{2\\pi}\\sin\\left(\\frac{2\\pi x}{L}\\right) \\right]_0^{L/2}$$",
    "$$P = \\frac{1}{L} \\left( \\frac{L}{2} - \\frac{L}{2\\pi}\\sin(\\pi) - 0 \\right) = \\frac{1}{L} \\left( \\frac{L}{2} - 0 \\right) = 0.5$$"
])

# --- CELL 17: CODE - ERRATA CORRECTION VERIFICATION ---
add_code([
    "# Verificación computacional del Potencial Eléctrico y Caja Cuántica",
    "",
    "# 1. Potencial Eléctrico en x = 4",
    "def v_correct_integrand(xp):",
    "    return 2.0 * xp / (4.0 - xp)",
    "",
    "correct_numeric, _ = quad(v_correct_integrand, 0.0, 3.0)",
    "correct_analytical = 8.0 * np.log(4.0) - 6.0",
    "",
    "print(\"=== CASO 1: POTENCIAL ELECTROSTÁTICO ===\")",
    "print(f\"Cálculo Numérico Correcto: V(4) = {correct_numeric:.6f} * k\")",
    "print(f\"Fórmula Analítica Correcta: V(4) = (8*ln(4) - 6) * k = {correct_analytical:.6f} * k\")",
    "print(f\"Valor reportado por la errata del PDF: -8.912 * k\\n\")",
    "",
    "# 2. Caja Cuántica (L = 1)",
    "L = 1.0",
    "def psi_sq(x):",
    "    return (2.0 / L) * (np.sin(np.pi * x / L))**2",
    "",
    "prob_numeric, _ = quad(psi_sq, 0.0, L / 2.0)",
    "",
    "print(\"=== CASO 2: CAJA CUÁNTICA UNIDIMENSIONAL ===\")",
    "print(f\"Probabilidad en [0, L/2] (Cálculo Numérico): P = {prob_numeric:.6f}\")",
    "print(f\"Probabilidad reportada por la errata del PDF (1 - 2/pi): P = {1.0 - 2.0/np.pi:.6f}\")",
    "",
    "# Visualizar la Caja Cuántica y la densidad de probabilidad",
    "x_box = np.linspace(0, L, 500)",
    "y_box = psi_sq(x_box)",
    "",
    "plt.figure(figsize=(9, 5))",
    "plt.plot(x_box, y_box, 'r-', linewidth=2.5, label='$|\\\\Psi(x)|^2$')",
    "",
    "# Sombrear la región [0, L/2]",
    "x_shade = np.linspace(0, L/2, 250)",
    "y_shade = psi_sq(x_shade)",
    "plt.fill_between(x_shade, y_shade, color='red', alpha=0.3, label=f'Probabilidad [0, L/2] = {prob_numeric:.1f}')",
    "",
    "plt.title('Densidad de Probabilidad de la Partícula en una Caja ($n=1$)', fontweight='bold')",
    "plt.xlabel('Posición $x$ (unidades de L)')",
    "plt.ylabel('Densidad $|\\\\Psi(x)|^2$')",
    "plt.xlim(0, L)",
    "plt.ylim(0, 2.2 / L)",
    "plt.grid(True, linestyle='--', alpha=0.5)",
    "plt.legend(frameon=True)",
    "plt.tight_layout()",
    "plt.show()"
])

# --- CELL 18: EXTENSIONS ---
add_markdown([
    "## 10. Extensiones de la Integral de Riemann",
    "",
    "A pesar de su inmensa utilidad, la integral de Riemann posee limitaciones importantes: requiere que las funciones sean acotadas y que el dominio de integración sea acotado. Esto dio lugar a generalizaciones clave del análisis real:",
    "",
    "### 10.1 Integral de Riemann-Stieltjes",
    "Permite integrar una función $f$ con respecto a otra función $\\alpha$ (llamada función de distribución o peso) en lugar de la variable muda $x$. Se denota por:",
    "$$\\int_a^b f(x) d\\alpha(x)$$",
    "y se define como el límite de las sumas modificadas:",
    "$$\\sum_{i=1}^n f(c_i) [\\beta(x_i) - \\beta(x_{i-1})]$$",
    "Es ampliamente utilizada en probabilidad para unificar el tratamiento de variables aleatorias discretas y continuas.",
    "",
    "### 10.2 Integral de Lebesgue",
    "La integral de Riemann se basa en realizar particiones verticales en el eje del dominio ($x$). Esto colapsa ante funciones altamente discontinuas como la **función de Dirichlet** (que vale 1 en racionales y 0 en irracionales), la cual no es integrable según Riemann.",
    "",
    "Henri Lebesgue propuso realizar particiones horizontales en el eje del rango o codominio ($y$). En lugar de multiplicar el valor de la función por el ancho de un intervalo, se multiplica el valor $y_j$ por la **medida del conjunto** de puntos en el dominio que mapean a dicho valor:",
    "$$\\int_X f d\\mu = \\lim \\sum y_j \\mu(f^{-1}(y_j))$$",
    "Esto proporciona un marco matemático mucho más robusto para el análisis funcional y la teoría de la medida.",
    "",
    "### 10.3 Integración en Espacios Métricos y no Euclidianos",
    "Generaliza los conceptos anteriores a espacios con distancias abstractas, como variedades diferenciales, utilizando herramientas de geometría diferencial, formas diferenciales y particiones de la unidad."
])

# --- CELL 19: CODE - RIEMANN VS LEBESGUE PARTITION SCHEMATIC ---
add_code([
    "# Gráfico esquemático de las particiones de Riemann (eje X) vs Lebesgue (eje Y)",
    "x_sch = np.linspace(0.1, 2.9, 300)",
    "y_sch = np.exp(-x_sch**2) + 0.5",
    "",
    "fig, (ax_r, ax_l) = plt.subplots(1, 2, figsize=(15, 6))",
    "",
    "# 1. Partición de Riemann",
    "ax_r.plot(x_sch, y_sch, 'k-', linewidth=2.5)",
    "n_r = 8",
    "x_r_nodes = np.linspace(0.1, 2.9, n_r + 1)",
    "for i in range(n_r):",
    "    x_p, x_n = x_r_nodes[i], x_r_nodes[i+1]",
    "    y_val = (np.exp(-x_p**2) + 0.5 + np.exp(-x_n**2) + 0.5) / 2.0",
    "    ax_r.bar(x_p, y_val, width=x_n-x_p, align='edge', alpha=0.3, ",
    "             edgecolor='blue', color='skyblue')",
    "ax_r.set_title('Partición de Riemann (Eje Dominio $x$)', fontweight='bold')",
    "ax_r.set_xlabel('$x$')",
    "ax_r.set_ylabel('$f(x)$')",
    "ax_r.grid(True, linestyle='--', alpha=0.5)",
    "",
    "# 2. Partición de Lebesgue",
    "ax_l.plot(x_sch, y_sch, 'k-', linewidth=2.5)",
    "y_l_nodes = np.linspace(0.5, 1.5, 6)",
    "for i in range(len(y_l_nodes)-1):",
    "    y_low, y_high = y_l_nodes[i], y_l_nodes[i+1]",
    "    ax_l.axhline(y_low, color='red', linestyle='--', alpha=0.6)",
    "    # Sombrear la franja horizontal",
    "    ax_l.fill_between(x_sch, y_low, y_high, where=(y_sch >= y_low) & (y_sch < y_high), ",
    "                      color='lightcoral', alpha=0.3, edgecolor='red')",
    "ax_l.axhline(y_l_nodes[-1], color='red', linestyle='--', alpha=0.6, label='Partición en Y')",
    "ax_l.set_title('Partición de Lebesgue (Eje Rango $y$)', fontweight='bold')",
    "ax_l.set_xlabel('$x$')",
    "ax_l.set_ylabel('$f(x)$')",
    "ax_l.legend(loc='upper right', frameon=True)",
    "ax_l.grid(True, linestyle='--', alpha=0.5)",
    "",
    "plt.tight_layout()",
    "plt.show()"
])

# --- CELL 20: EXERCISES AND SOLUTIONS ---
add_markdown([
    "## 11. Ejercicios Resueltos (De la sección de Ejercicios Propuestos del PDF)",
    "",
    "A continuación, resolvemos de manera analítica y formal los ejercicios propuestos en el texto original.",
    "",
    "### Ejercicio 1: Cálculo por Definición y Sumas de Riemann",
    "**Enunciado:** Calcular la integral definida $\\int_0^2 x^2 dx$ utilizando la definición de la integral de Riemann con particiones regulares y puntos medios.",
    "",
    "**Solución:**",
    "1. **Partición regular:** Dividimos el intervalo $[0, 2]$ en $n$ partes de igual longitud $\\Delta x = \\frac{2-0}{n} = \\frac{2}{n}$. Los nodos son $x_i = a + i\\Delta x = \\frac{2i}{n}$ para $i = 0, 1, \\dots, n$.",
    "2. **Puntos medios ($c_i$):**",
    "   $$c_i = \\frac{x_{i-1} + x_i}{2} = \\frac{1}{2} \\left( \\frac{2(i-1)}{n} + \\frac{2i}{n} \\right) = \\frac{2i - 1}{n}$$",
    "3. **Suma de Riemann:**",
    "   $$S_n = \\sum_{i=1}^n f(c_i) \\Delta x = \\sum_{i=1}^n \\left( \\frac{2i - 1}{n} \\right)^2 \\left( \\frac{2}{n} \\right) = \\frac{2}{n^3} \\sum_{i=1}^n (4i^2 - 4i + 1)$$",
    "   $$S_n = \\frac{2}{n^3} \\left[ 4 \\sum_{i=1}^n i^2 - 4 \\sum_{i=1}^n i + \\sum_{i=1}^n 1 \\right]$$",
    "   Usando las fórmulas de sumas conocidas:",
    "   $$\\sum_{i=1}^n i^2 = \\frac{n(n+1)(2n+1)}{6}, \\quad \\sum_{i=1}^n i = \\frac{n(n+1)}{2}, \\quad \\sum_{i=1}^n 1 = n$$",
    "   Sustituyendo:",
    "   $$S_n = \\frac{2}{n^3} \\left[ 4 \\left( \\frac{n(n+1)(2n+1)}{6} \\right) - 4 \\left( \\frac{n(n+1)}{2} \\right) + n \\right]$$",
    "   $$S_n = \\frac{2}{n^3} \\left[ \\frac{2}{3}n(n+1)(2n+1) - 2n(n+1) + n \\right]$$",
    "   Al tomar el límite cuando $n \\to \\infty$, los términos de menor grado en el numerador se anulan y solo sobreviven los coeficientes del término $n^3$:",
    "   $$\\lim_{n \\to \\infty} S_n = \\lim_{n \\to \\infty} \\frac{2}{n^3} \\left[ \\frac{4}{3}n^3 + O(n^2) \\right] = 2 \\times \\frac{4}{3} = \\frac{8}{3}$$",
    "",
    "---",
    "",
    "### Ejercicio 2: Criterio de Integrabilidad",
    "**Enunciado:** Sea $f(x) = 1/x$ en el intervalo $[1, 3]$. Determinar si $f(x)$ es integrable en ese intervalo según la definición y criterios de la integral de Riemann.",
    "",
    "**Solución:**",
    "1. **Continuidad:** La función $f(x) = 1/x$ tiene una única discontinuidad (asíntota infinita) en $x = 0$. Dado que $0 \\notin [1, 3]$, la función es perfectamente continua en todo el intervalo cerrado $[1, 3]$.",
    "2. **Acotamiento:** Para todo $x \\in [1, 3]$, se cumple que $\\frac{1}{3} \\le f(x) \\le 1$. La función está acotada en el intervalo.",
    "3. **Teorema de Integrabilidad:** Dado que $f(x)$ es continua en el intervalo cerrado $[1, 3]$ (y por tanto acotada y sin discontinuidades en dicho soporte), es integrable según Riemann en $[1, 3]$.",
    "",
    "---",
    "",
    "### Ejercicio 3: Teorema Fundamental del Cálculo",
    "**Enunciado:** Dada $F(x) = \\int_0^x \\sin(t^2) dt$, encuentre $F'(x)$ utilizando el Teorema Fundamental del Cálculo.",
    "",
    "**Solución:**",
    "Por el Primer Teorema Fundamental del Cálculo, si $f(t) = \\sin(t^2)$ es una función continua en toda la recta real $\\mathbb{R}$ (lo cual es cierto por ser la composición de funciones continuas), entonces la función de acumulación $F(x) = \\int_0^x f(t) dt$ es derivable en cualquier intervalo cerrado, y se cumple que:",
    "$$F'(x) = \\frac{d}{dx} \\left[ \\int_0^x \\sin(t^2) dt \\right] = \\sin(x^2)$$",
    "",
    "---",
    "",
    "### Ejercicio 4: Distancia Recorrida y Desplazamiento",
    "**Enunciado:** Un objeto se mueve a lo largo de una línea recta con velocidad $v(t) = t^2 - 3t + 2$ (en m/s, con $t$ en segundos). ¿Cuál es la distancia total recorrida por el objeto en los primeros 3 segundos?",
    "",
    "**Solución:**",
    "En física, es crucial diferenciar entre **desplazamiento** (integral directa de la velocidad) y **distancia total recorrida** (integral del valor absoluto de la velocidad).",
    "",
    "1. **Cero de la velocidad:** Analizamos dónde cambia de signo la velocidad:",
    "   $$v(t) = t^2 - 3t + 2 = (t-1)(t-2) = 0 \\implies t = 1\\text{ s}, \\; t = 2\\text{ s}$$",
    "   - En $[0, 1]$: $v(t) \\ge 0$",
    "   - En $[1, 2]$: $v(t) \\le 0$",
    "   - En $[2, 3]$: $v(t) \\ge 0$",
    "2. **Distancia Total Recorrida ($d$):**",
    "   $$d = \\int_0^3 |v(t)| dt = \\int_0^1 (t^2 - 3t + 2) dt - \\int_1^2 (t^2 - 3t + 2) dt + \\int_2^3 (t^2 - 3t + 2) dt$$",
    "   Definimos la primitiva $V(t) = \\frac{t^3}{3} - \\frac{3t^2}{2} + 2t$:",
    "   - Tramo 1: $V(1) - V(0) = \\left( \\frac{1}{3} - \\frac{3}{2} + 2 \\right) - 0 = \\frac{5}{6}\\text{ m}$",
    "   - Tramo 2: $V(2) - V(1) = \\left( \\frac{8}{3} - 6 + 4 \\right) - \\frac{5}{6} = \\frac{2}{3} - \\frac{5}{6} = -\\frac{1}{6}\\text{ m} \\implies |V(2) - V(1)| = \\frac{1}{6}\\text{ m}$",
    "   - Tramo 3: $V(3) - V(2) = \\left( 9 - \\frac{27}{2} + 6 \\right) - \\frac{2}{3} = \\frac{3}{2} - \\frac{2}{3} = \\frac{5}{6}\\text{ m}$",
    "   Suma de distancias en valor absoluto:",
    "   $$d = \\frac{5}{6} + \\frac{1}{6} + \\frac{5}{6} = \\frac{11}{6} \\approx 1.833\\text{ m}$$",
    "3. **Desplazamiento Neto ($\\Delta s$):**",
    "   $$\\Delta s = \\int_0^3 v(t) dt = V(3) - V(0) = \\frac{5}{6} - \\frac{1}{6} + \\frac{5}{6} = \\frac{9}{6} = 1.5\\text{ m}$$"
])

# --- CELL 21: CONCLUSION & BIBLIOGRAPHY ---
add_markdown([
    "## 12. Conclusión y Bibliografía",
    "",
    "La integral de Riemann provee la base fundamental del cálculo integral clásico. Al complementar el análisis analítico con simulaciones numéricas (Trapecio y Simpson), no solo podemos aproximar integrales complejas con alta precisión, sino que también podemos validar y depurar erratas comunes que persisten en textos tradicionales.",
    "",
    "### Bibliografía",
    "[1] T. M. Apóstol, *Calculus*, 2a ed., Wiley, 1967. (Sección 1.12 - 1.15).",
    "[2] J. Stewart, *Cálculo de una Variable: Trascendentes Tempranas*, 7a ed., Cengage Learning, 2012. (Sección 5.1 - 5.5).",
    "[3] G. B. Thomas Jr. y M. D. Weir, *Cálculo: Una variable*, 11a ed., Pearson Educación, 2012."
])

# Guardar a archivo
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"Cuaderno generado con éxito en: {output_path}")
